//mycodes.
// console.log("hiiii");
// let a=window;
// console.log(a);

//codewithharry codes

console.log('This is tut 11');
let a = window.document;
alert('hello Devil');
a = prompt('This will destroy your computer. Type your name');
console.log(a);          

a = confirm('Are you sure you want to delete this page?');
console.log(a);          
a = window.innerHeight;
a = innerWidth;
a = scrollY;
a = location.toString();
a = window.history;
console.log(a);          
