// console.log("Hello");
// let x=4;
// let y=6;
// let z=x+y;
// let c=x-y;
// let v=x*y;
// let b=x/y;//gives quotient
// let t=x%y;//gives remainder
// console.log(z);
// console.log(c);
// console.log(v);
// console.log(b);
// console.log(t);
// let G=Math;
// G=Math.asin(0.6);
// G=Math.floor(2.6);
// console.log(G);

// console.log("Welcome to tutorial number 23");
// let x = 3;
// let y = 6;
// let z;
// z = x+y;
// z = x-y;
// z = x*y;
// z = x/y;

// Exploring the Math object
z = Math;
z = Math.PI;
z = Math.E;
z = Math.round(5.4);
z = Math.ceil(5.3);
z = Math.floor(-5.3);
z = Math.abs(5);
z = Math.sqrt(64);
z = Math.pow(2, 3);
z = Math.min(2, 3, 34,234, 2342,34);
z = Math.max(2, 3, 34,234,34);
z = Math.random();
z = 100*Math.random()
z = Math.ceil(50 + (100-50)*Math.random())
// a = (0, 1)
// a100 = a*100 = (0, 100)
// a10_100 = 10+a*(100 - 10)

console.log(z);

// 3
// 2.8
// 2
// 1
// 0
// -1
// -2
// -2.7
// -3
 